### ISSUE TITLE
sage cannot move to boundaries

### ISSUE THREAD

**Issue by Arkk92** [Ojka91/element-core#38]
Note the red dots are the places where the mouse was clicked.

![image](https://user-images.githubusercontent.com/117123822/212116518-19529473-748a-4cd9-bb69-190df0e0aee2.png)

![image](https://user-images.githubusercontent.com/117123822/212117157-16da07e2-4115-4aa6-a630-0bdcca8722e3.png)

**Comment by Ojka91** [comment]
I cant reproduce

**Comment by Arkk92** [comment]
Looks like in the latest commits this bug was fixed.

**Comment by Arkk92** [comment]
Closing this ticket. I'll reopen in case the bug happens again
